server:
  port: 8081

spring:
  application:
    name: forum
# thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false

#数据库链接信息
  datasource:
    username: root
    password: xiaomingmmm
    url: jdbc:mysql://localhost:3306/forum?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
#mybatis配置信息
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.wtu.sj.entity
  configuration:
    map-underscore-to-camel-case: true

#分页插件
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

